---
name: Test on Docker Sandbox

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, master]
    paths:
      - "src/asb/internal/cmdrunner/**.go"
      - ".github/workflows/test-on-docker-sandbox.yaml"
  pull_request:
    branches: [main, master]
    paths:
      - "src/asb/internal/cmdrunner/**.go"
      - ".github/workflows/test-on-docker-sandbox.yaml"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: read

jobs:

  # Run it locally with https://github.com/nektos/act
  # act -j testOnDockerSandbox
  testOnDockerSandbox:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          cache-dependency-path: "src/asb/go.mod"
          go-version-file: "src/asb/go.mod"

      # Ref: https://github.com/actions/cache/blob/main/examples.md#go---modules
      - uses: actions/cache@v6
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        working-directory: "src/asb"
        run: "make build"  # output in bin/asb

      - name: Test basic CLI commands
        run: |
          ./src/asb/bin/asb --mode=docker help > /dev/null
          ./src/asb/bin/asb --mode=docker version

      - name: Test important CLI commands
        # env:
        #    LOG_LEVEL: DEBUG  # Set log level to DEBUG for more verbose output
        run: |
          shopt -s expand_aliases
          alias asb="${PWD}/src/asb/bin/asb --mode=docker"
          # Now the commands
          # Python related
          asb pip --version
          asb poetry --version
          asb uv --version
          asb uvx --version 
          # JavaScript related
          asb bun --version
          asb node --version
          asb pnpm --version
          asb npm --version
          asb npx --version
          asb yarn --version
          # Others
          # asb cabal --version
          asb cargo --version
          asb gem --version
          asb zig version
